"""empty message

Revision ID: d135dffe7af9
Revises: ff81f6cfd25c
Create Date: 2019-08-05 15:12:55.981576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd135dffe7af9'
down_revision = 'ff81f6cfd25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('app_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'app_name')
    # ### end Alembic commands ###
